version: '3'

services:
  redis:
    container_name: redis
    image: redis:7.2.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/usr/local/etc/redis/redis.conf

volumes:
  redis_data:
    driver: local
